#!/usr/bin/env -S bash -e
# pre-commit hook for the current Git repository.

# shellcheck source=lib/functions
. ./.githooks/lib/functions

run_markdown_check() {
    cd "${git_sync_repo}"
    print_info "Run Markdown check"
    python_command="python3"
    if ! command -v "${python_command}" >/dev/null 2>&1 && ! "${python_command}" -c "import this"; then
        python_command="python"
        if ! command -v "${python_command}" >/dev/null 2>&1 && ! "${python_command}" -c "import this"; then
            print_warn "Python is not installed on this system!"
            return 0
        fi
    fi
    "${python_command}" ./.githooks/scripts/change_markdown_links.py >/dev/null 2>&1
}

run_git_diff_check() {
    # shellcheck disable=SC2154
    cd "${git_sync_repo}"
    git add -A
    LESS="" DELTA_PAGER="" PAGER="" git diff --cached
    LESS="" DELTA_PAGER="" PAGER="" git diff
}

run_health_check() {
    print_info "Run Markdown check"
    run_markdown_check
}

cleanup() {
    exit_code="${1}"
    if [[ "${exit_code}" -ne 0 ]]; then
        print_fail "Something went wrong with git config or with healthcheck! Exit code: ${exit_code}"
    fi
    # shellcheck disable=2086
    exit ${exit_code}
}

trap "cleanup" EXIT

print_info "Hello, ${git_username}, let's try to sync your changes."

print_info "Running Healthcheck..."
run_health_check

print_okay "Healthcheck is OK!"
